/**
 * Bundle the media helper into one file.
 *
 * The Tauri shell runs `node.exe mediaHelper.bundle.mjs` from a resource
 * directory that contains nothing else — no `server/`, no `node_modules`. So
 * every local module *and* `youtubei.js` have to end up in a single script.
 *
 * Output: server-dist/mediaHelper.bundle.mjs
 */

import { build } from 'esbuild'
import { mkdir, rm } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const entry = path.join(root, 'server', 'mediaHelper.mjs')
const outDir = path.join(root, 'server-dist')
const outFile = path.join(outDir, 'mediaHelper.bundle.mjs')

// youtubei.js pulls in jsdom/undici and reaches for optional native bits.
// It bundles cleanly, but anything genuinely unresolvable is left as a runtime
// import so a failure is a clear error at startup rather than a build failure
// with no output.
const EXTERNAL = ['bun:sqlite', 'better-sqlite3']

await rm(outDir, { recursive: true, force: true })
await mkdir(outDir, { recursive: true })

await build({
  entryPoints: [entry],
  outfile: outFile,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  // The helper is spawned with stdio discarded; keep it quiet.
  logLevel: 'warning',
  legalComments: 'none',
  minify: false,
  sourcemap: false,
  external: EXTERNAL,
  banner: {
    js: '// Crest media helper — generated by scripts/build-helper.mjs. Do not edit.',
  },
  define: {
    'process.env.NODE_ENV': '"production"',
  },
})

console.log(`[build-helper] wrote ${path.relative(root, outFile)}`)